# Generated by Django 6.0.7 on 2026-07-26 17:42

import aspep.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'CPF deve conter 11 dígitos numéricos.')], verbose_name='CPF')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('status', models.CharField(choices=[('P', 'PENDENTE'), ('R', 'REFAZER'), ('C', 'CORRETO')], default='P', max_length=1, verbose_name='Status')),
                ('microfilmagens', models.FileField(upload_to=aspep.utils.cliente_microfilmagens_upload_to, verbose_name='Microfilmagens')),
                ('extrato', models.FileField(upload_to=aspep.utils.cliente_extrato_upload_to, verbose_name='Extrato')),
                ('observacoes_adcionais', models.TextField(blank=True, verbose_name='Observações adicionais')),
                ('data_de_modificacao', models.DateTimeField(auto_now=True, verbose_name='Data de modificação')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
