# Generated by Django 6.0.7 on 2026-08-01 17:18

import aspep.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspep', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='data_de_modificacao',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='extrato',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='microfilmagens',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='observacoes_adcionais',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='status',
        ),
        migrations.CreateModel(
            name='Calculo',
            fields=[
                ('inscricao', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=10, verbose_name='Valor')),
                ('status', models.CharField(choices=[('P', 'PENDENTE'), ('R', 'REFAZER'), ('C', 'CORRETO')], default='P', max_length=1, verbose_name='Status')),
                ('microfilmagens', models.FileField(upload_to=aspep.utils.cliente_microfilmagens_upload_to, verbose_name='Microfilmagens')),
                ('extrato', models.FileField(upload_to=aspep.utils.cliente_extrato_upload_to, verbose_name='Extrato')),
                ('observacoes_adcionais', models.TextField(blank=True, verbose_name='Observações adicionais')),
                ('data_de_modificacao', models.DateTimeField(auto_now=True, verbose_name='Data de modificação')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aspep.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Cálculo',
                'verbose_name_plural': 'Cálculos',
            },
        ),
    ]
